name: delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  fluttertoast: ^8.2.11
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.2
  shared_preferences: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  salomon_bottom_bar: ^3.3.2
  flutter_advanced_drawer: ^1.4.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  animated_text_kit: ^4.2.3
  lottie: ^3.2.0
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  

  fonts:
    - family: San-Francisco-Pro-Fonts-master
      fonts:
        - asset: assets\fonts\San-Francisco-Pro-Fonts-master\SF-Pro-Display-Heavy.otf
        
          style: italic

    - family: SF-Pro-Italic.ttf
      fonts:
        - asset: assets\fonts\San-Francisco-Pro-Fonts-master\SF-Pro-Text-Regular.otf
          style: italic
